### ISSUE TITLE
Error: CKEditor not loaded when updating blog

### ISSUE THREAD

**Issue by ondics** [ckan/ckanext-pages#125]
Error description: 
* CKEditor is enabled
* Creation of a blog article works
* When updating of a blog article, the editor is missing

Debugging (using Docker image `openknowledge/ckan-base:2.9`) results in: 

The two files cannot be loaded:
```
https://<production-ckan-hostname>/blog_edit/skins/moono-lisa/editor_gecko.css?t=L0QD
https://<production-ckan-hostname>/blog_edit/lang/de.js?t=L0QD
```

When using this extension as developer everything works (Docker image `openknowledge/ckan-dev:2.9`):

The two files are loaded with a different URLs: 
```
https://<developer-ckan-hostname>/skins/moono-lisa/editor_gecko.css?t=L0QD
https://<developer-ckan-hostname>/lang/de.js?t=L0QD
```

In `.env` this extension is configured using
```
CKANEXT__PAGES__ABOUT_MENU=False
CKANEXT__PAGES__ALLOW_HTML=True
CKANEXT__PAGES__EDITOR=ckeditor
```

Is that a bug in the extension? Am I missing something? Config error?

**Comment by pdelboca** [comment]
I'm having the exact same issue. I tried to debug it today but couldn't find any reasonable solution. Looks like there is something wrong on how ckanext-pages is serving/accessing webassets.

I also don't understand why is appending `/pages_edit` when `debug=False`.

@smotornyuk any idea what is going on here?

**Comment by pdelboca** [comment]
Thanks for your answer @smotornyuk .

I'm just trying to understand what changed since this feature stop working when updating from `2.9` to `2.10`. That's why I'm pointing to `ckanext-pages` registering or loading assets differently than before.

CKAN 2.9 with ckanext-pages v0.3.7:
![Screenshot from 2023-06-07 12-05-07](https://github.com/ckan/ckanext-pages/assets/6672339/fc6b3ea0-7864-4f22-856e-ceb22d44fd42)
  
  CKAN 2.10 with ckanext-pages v0.5.1:
  
![Screenshot from 2023-06-07 12-13-17](https://github.com/ckan/ckanext-pages/assets/6672339/9005b949-9d67-448f-b3e7-2e1046888863)

That's why I'm trying to get more insights on how webassets are handled. I'll keep looking into this!

**Comment by smotornyuk** [comment]
I suspect, somebody has overriden [this hack](https://github.com/ckan/ckanext-pages/commit/ae645a2828a510a67445d3a05b2c3ff06ebf80ac)
