### ISSUE TITLE
Error 500 with ckan 2.5

### ISSUE THREAD

**Issue by hlafuente** [ckan/ckanext-pages#58]
Good morning,

I have an error in a ckan 2.5. When I click on the page icon I get a 500 error.

The error is:
File '/usr/lib/ckan/default/src/ckanext-pages/ckanext/pages/plugin.py', line 94 in get_plus_icon
   ckan_version = float (h.ckan_version () [0: 3])
AttributeError: 'module' object has no attribute 'ckan_version'

I think my ckan.lib.helpers does not have ckan_version()

This is my log file: [logerrorpages.zip](https://github.com/ckan/ckanext-pages/files/1317896/logerrorpages.zip)

Bye.

**Comment by torfsen** [comment]
The problem is that `get_plus_icon` uses CKAN's helper function `ckan_version` which was [introduced only recently](https://github.com/ckan/ckan/commit/a2e30febe25aabcbcb34b4678489655086fa81f2) and is therefore not available on older versions of CKAN. Instead of `ckan_version` we should use [`check_ckan_version`](http://docs.ckan.org/en/ckan-2.7.0/extensions/plugins-toolkit.html#ckan.plugins.toolkit.ckan.plugins.toolkit.check_ckan_version) from the toolkit, which has been available for a much longer time.

Unfortunately the tests did not detect this problem, [they ran successfully on CKAN 2.5 when the change was made](https://travis-ci.org/ckan/ckanext-pages/jobs/231042885). So this might be a good idea to improve our test coverage, too.

CC @mattfullerton: the breaking change is in your commit fae750587970d190fc5547a2c323bc11b3858957 (which I've reviewed :sob:)

**Comment by mattfullerton** [comment]
@torfsen Only seeing this now. Will you fix it or should I?

**Comment by torfsen** [comment]
@mattfullerton I'll be working on it when I find time.
